// U.S. states + D.C. -> capital. Static, evergreen factual data (capitals don't change).
const US_STATES = [
  { name: "Alabama", capital: "Montgomery" },
  { name: "Alaska", capital: "Juneau" },
  { name: "Arizona", capital: "Phoenix" },
  { name: "Arkansas", capital: "Little Rock" },
  { name: "California", capital: "Sacramento" },
  { name: "Colorado", capital: "Denver" },
  { name: "Connecticut", capital: "Hartford" },
  { name: "Delaware", capital: "Dover" },
  { name: "Florida", capital: "Tallahassee" },
  { name: "Georgia", capital: "Atlanta" },
  { name: "Hawaii", capital: "Honolulu" },
  { name: "Idaho", capital: "Boise" },
  { name: "Illinois", capital: "Springfield" },
  { name: "Indiana", capital: "Indianapolis" },
  { name: "Iowa", capital: "Des Moines" },
  { name: "Kansas", capital: "Topeka" },
  { name: "Kentucky", capital: "Frankfort" },
  { name: "Louisiana", capital: "Baton Rouge" },
  { name: "Maine", capital: "Augusta" },
  { name: "Maryland", capital: "Annapolis" },
  { name: "Massachusetts", capital: "Boston" },
  { name: "Michigan", capital: "Lansing" },
  { name: "Minnesota", capital: "Saint Paul" },
  { name: "Mississippi", capital: "Jackson" },
  { name: "Missouri", capital: "Jefferson City" },
  { name: "Montana", capital: "Helena" },
  { name: "Nebraska", capital: "Lincoln" },
  { name: "Nevada", capital: "Carson City" },
  { name: "New Hampshire", capital: "Concord" },
  { name: "New Jersey", capital: "Trenton" },
  { name: "New Mexico", capital: "Santa Fe" },
  { name: "New York", capital: "Albany" },
  { name: "North Carolina", capital: "Raleigh" },
  { name: "North Dakota", capital: "Bismarck" },
  { name: "Ohio", capital: "Columbus" },
  { name: "Oklahoma", capital: "Oklahoma City" },
  { name: "Oregon", capital: "Salem" },
  { name: "Pennsylvania", capital: "Harrisburg" },
  { name: "Rhode Island", capital: "Providence" },
  { name: "South Carolina", capital: "Columbia" },
  { name: "South Dakota", capital: "Pierre" },
  { name: "Tennessee", capital: "Nashville" },
  { name: "Texas", capital: "Austin" },
  { name: "Utah", capital: "Salt Lake City" },
  { name: "Vermont", capital: "Montpelier" },
  { name: "Virginia", capital: "Richmond" },
  { name: "Washington", capital: "Olympia" },
  { name: "West Virginia", capital: "Charleston" },
  { name: "Wisconsin", capital: "Madison" },
  { name: "Wyoming", capital: "Cheyenne" },
  { name: "District of Columbia", capital: null, note: "D.C. is not a state and has no governor, senators, or capital of its own." },
  { name: "Puerto Rico", capital: "San Juan", note: "U.S. territory — no U.S. senators; represented by a nonvoting Resident Commissioner." },
  { name: "Guam", capital: "Hagåtña", note: "U.S. territory — no U.S. senators; represented by a nonvoting Delegate." },
  { name: "U.S. Virgin Islands", capital: "Charlotte Amalie", note: "U.S. territory — no U.S. senators; represented by a nonvoting Delegate." },
  { name: "American Samoa", capital: "Pago Pago", note: "U.S. territory — no U.S. senators; represented by a nonvoting Delegate." },
  { name: "Northern Mariana Islands", capital: "Saipan", note: "U.S. territory — no U.S. senators; represented by a nonvoting Delegate." },
];
